# GitHub OAuth2 Client
quarkus.oidc-client.github.auth-server-url=https://github.com
quarkus.oidc-client.github.client-id=
quarkus.oidc-client.github.credentials.secret=
quarkus.oidc-client.github.discovery-enabled=false
quarkus.oidc-client.github.token-path=/login/oauth/access_token
quarkus.oidc-client.github.grant.type=code
quarkus.oidc-client.github.redirect-uri=http://localhost:9095/auth/social/github/callback
quarkus.oidc-client.github.headers.Accept=application/json

quarkus.oidc-client.google.auth-server-url=https://accounts.google.com
quarkus.oidc-client.google.client-id=
quarkus.oidc-client.google.credentials.secret=
quarkus.oidc-client.google.discovery-enabled=true
quarkus.oidc-client.google.grant.type=code
quarkus.oidc-client.google.redirect-uri=http://localhost:9095/auth/social/google/callback
quarkus.oidc-client.google.scopes=openid,profile,email

quarkus.mailer.host=smtp.mailersend.net
quarkus.mailer.port=587
quarkus.mailer.auth=true
quarkus.mailer.username=
quarkus.mailer.password=
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.ssl=false
quarkus.mailer.from=
quarkus.mailer.mock=false

quarkus.mailer.secondary.host=smtp.secondary.com
quarkus.mailer.secondary.port=587
quarkus.mailer.secondary.start-tls=REQUIRED
quarkus.mailer.secondary.ssl=false
quarkus.mailer.secondary.auth=true
quarkus.mailer.secondary.username=
quarkus.mailer.secondary.password=
quarkus.mailer.secondary.from=
quarkus.mailer.secondary.mock=false

# Google UserInfo API
google.userinfo/mp-rest/url=https://www.googleapis.com/oauth2/v3/userinfo

quarkus.keycloak.devservices.enabled=false

github.api/mp-rest/url=https://api.github.com

# Frontend
frontend.url=http://localhost:4200

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=
quarkus.datasource.password=
quarkus.datasource.jdbc.url=

mp.jwt.verify.publickey.location=classpath:publicKey.pem
mp.jwt.verify.issuer=livepoll-auth

smallrye.jwt.sign.key.location=classpath:privateKey.pem

quarkus.native.resources.includes=*.pem,*.html,templates/**

quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.locations=db/migration

quarkus.http.port=8084
%prod.quarkus.http.port=${PORT:8080}

quarkus.application.name=auth-service

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:9095
quarkus.http.cors.credentials=true
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS

%prod.cookie.secure=true

%dev.cookie.secure=true

rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

mp.messaging.outgoing.user-registration.connector=smallrye-rabbitmq
mp.messaging.outgoing.user-registration.exchange.name=user-registration
mp.messaging.outgoing.user-registration.routing-key=user-registration

mp.messaging.incoming.registration-response.connector=smallrye-rabbitmq
mp.messaging.incoming.registration-response.queue.name=auth-service-registration-response-queue
mp.messaging.incoming.registration-response.exchange.name=registration-response
mp.messaging.incoming.registration-response.routing-key=registration-response

mp.messaging.incoming.user-deleted.connector=smallrye-rabbitmq
mp.messaging.incoming.user-deleted.exchange.name=user-deleted
mp.messaging.incoming.user-deleted.queue.name=auth-service-user-deleted-queue
mp.messaging.incoming.user-deleted.routing-key=user-deleted