quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=
quarkus.datasource.password=
quarkus.datasource.jdbc.url=
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.locations=db/migration

mp.jwt.verify.publickey.location=classpath:publicKey.pem
mp.jwt.verify.issuer=livepoll-auth

quarkus.http.port=8087
%prod.quarkus.http.port=${PORT:8080}

quarkus.native.resources.includes=*.pem

# Configurações do RabbitMQ
rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

mp.messaging.incoming.poll-created.connector=smallrye-rabbitmq
mp.messaging.incoming.poll-created.exchange.name=poll-created
mp.messaging.incoming.poll-created.queue.name=poll-read-service-poll-created-queue
mp.messaging.incoming.poll-created.routing-key=poll-created

mp.messaging.incoming.poll-updated.connector=smallrye-rabbitmq
mp.messaging.incoming.poll-updated.exchange.name=poll-updated
mp.messaging.incoming.poll-updated.queue.name=poll-read-service-poll-updated-queue
mp.messaging.incoming.poll-updated.routing-key=poll-updated

mp.messaging.incoming.poll-deleted.connector=smallrye-rabbitmq
mp.messaging.incoming.poll-deleted.exchange.name=poll-deleted
mp.messaging.incoming.poll-deleted.queue.name=poll-read-service-poll-deleted-queue
mp.messaging.incoming.poll-deleted.routing-key=poll-deleted

mp.messaging.incoming.option-removed.connector=smallrye-rabbitmq
mp.messaging.incoming.option-removed.exchange.name=option-removed
mp.messaging.incoming.option-removed.queue.name=poll-read-service-option-removed-queue
mp.messaging.incoming.option-removed.routing-key=option-removed

mp.messaging.incoming.vote-cast.connector=smallrye-rabbitmq
mp.messaging.incoming.vote-cast.exchange.name=vote-cast
mp.messaging.incoming.vote-cast.queue.name=poll-read-service-vote-cast-queue
mp.messaging.incoming.vote-cast.routing-key=vote-cast

mp.messaging.outgoing.feed-ready.connector=smallrye-rabbitmq
mp.messaging.outgoing.feed-ready.exchange.name=feed-ready
mp.messaging.outgoing.feed-ready.routing-key=feed-ready

mp.messaging.outgoing.poll-vote-cast.connector=smallrye-rabbitmq
mp.messaging.outgoing.poll-vote-cast.exchange.name=poll-vote-cast
mp.messaging.outgoing.poll-vote-cast.routing-key=poll-vote-cast

mp.messaging.outgoing.poll-milestone.connector=smallrye-rabbitmq
mp.messaging.outgoing.poll-milestone.exchange.name=poll-milestone
mp.messaging.outgoing.poll-milestone.routing-key=poll-milestone

mp.messaging.incoming.user-deleted.connector=smallrye-rabbitmq
mp.messaging.incoming.user-deleted.exchange.name=user-deleted
mp.messaging.incoming.user-deleted.queue.name=poll-read-service-user-deleted-queue
mp.messaging.incoming.user-deleted.routing-key=user-deleted

mp.messaging.incoming.user-updated.connector=smallrye-rabbitmq
mp.messaging.incoming.user-updated.exchange.name=user-updated
mp.messaging.incoming.user-updated.queue.name=poll-read-service-user-updated-queue
mp.messaging.incoming.user-updated.routing-key=user-updated