quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=
quarkus.datasource.password=
quarkus.datasource.jdbc.url=

quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.locations=db/migration

mp.jwt.verify.publickey.location=classpath:publicKey.pem
mp.jwt.verify.issuer=livepoll-auth

quarkus.native.resources.includes=*.pem

quarkus.http.port=8085
%prod.quarkus.http.port=${PORT:8080}

# Configurações do RabbitMQ
rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

mp.messaging.incoming.user-registration.connector=smallrye-rabbitmq
mp.messaging.incoming.user-registration.queue.name=user-service-user-registration-queue
mp.messaging.incoming.user-registration.exchange.name=user-registration
mp.messaging.incoming.user-registration.routing-key=user-registration

mp.messaging.outgoing.registration-response.connector=smallrye-rabbitmq
mp.messaging.outgoing.registration-response.exchange.name=registration-response
mp.messaging.outgoing.registration-response.routing-key=registration-response

mp.messaging.outgoing.user-updated.connector=smallrye-rabbitmq
mp.messaging.outgoing.user-updated.exchange.name=user-updated
mp.messaging.outgoing.user-updated.routing-key=user-updated

mp.messaging.outgoing.user-deleted.connector=smallrye-rabbitmq
mp.messaging.outgoing.user-deleted.exchange.name=user-deleted
mp.messaging.outgoing.user-deleted.routing-key=user-deleted