quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=
quarkus.datasource.password=
quarkus.datasource.jdbc.url=
quarkus.http.port=8088
%prod.quarkus.http.port=${PORT:8080}
quarkus.application.name=vote-service

mp.jwt.verify.publickey.location=classpath:publicKey.pem
mp.jwt.verify.issuer=livepoll-auth

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=https://localhost:4200
quarkus.http.cors.credentials=true
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS
quarkus.log.category."io.quarkus.vertx.http.cors".level=DEBUG

quarkus.native.resources.includes=*.pem

# Configurações do RabbitMQ
rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

mp.messaging.outgoing.vote-cast.connector=smallrye-rabbitmq
mp.messaging.outgoing.vote-cast.exchange.name=vote-cast
mp.messaging.outgoing.vote-cast.routing-key=vote-cast

mp.messaging.incoming.poll-closed.connector=smallrye-rabbitmq
mp.messaging.incoming.poll-closed.exchange.name=poll-closed
mp.messaging.incoming.poll-closed.queue.name=vote-service-poll-closed-queue
mp.messaging.incoming.poll-closed.routing-key=poll-closed

mp.messaging.outgoing.poll-closed-notification.connector=smallrye-rabbitmq
mp.messaging.outgoing.poll-closed-notification.exchange.name=poll-closed-notification
mp.messaging.outgoing.poll-closed-notification.routing-key=poll-closed-notification